In [1]:
import pandas as pd

In [2]:
splits = {'train': 'train.csv', 'validation': 'dev.csv', 'test': 'test.csv'}
df = pd.read_csv("hf://datasets/ibm-research/argument_quality_ranking_30k/" + splits["train"])

/home/dimitri/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [17]:
df.head(3)

,argument,topic,set,WA,MACE-P,stance_WA,stance_WA_conf,abandon,abandoned,ability,...,worse,worst,worth,wouldn,wrong,year,years,young,younger,zoos
0,"""marriage"" isn't keeping up with the times. a...",We should abandon marriage,train,0.846165,0.297659,1,1.0,0.288133,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,.a multi-party system would be too confusing a...,We should adopt a multi-party system,train,0.891271,0.726133,-1,1.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,`people reach their limit when it comes to the...,Assisted suicide should be a criminal offence,train,0.730395,0.225212,-1,1.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. CrÃ©ez le vectoriseur
vectorizer = TfidfVectorizer(stop_words='english', max_features=1000)

# 2. Calculez la matrice TF-IDF sur la colonne 'argument'
tfidf_matrix = vectorizer.fit_transform(df['argument'])

# 3. Transformez en DataFrame
df_tfidf = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=df.index
)

df_tfidf.head()

,abandon,abandoned,ability,able,abolish,abolished,abolishing,abolition,absolutely,abuse,...,worse,worst,worth,wouldn,wrong,year,years,young,younger,zoos
0,0.288133,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.373523,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
def sentence_to_tfidf(sentence):
    """
    Transforme une phrase (str) en Series TF-IDF
    basÃ©e sur le vectorizer dÃ©jÃ  entraÃ®nÃ©.
    """
    tfidf_vec = vectorizer.transform([sentence])
    return tfidf_vec.toarray()[0]
a = sentence_to_tfidf("abandon isn't keeping up with the")

In [16]:
a[:30]

array([0.54940679, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])